name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry install  # Second time to install project
      - name: Run tests
        run: poe codecov  # TODO: Use `poe ci`
      - name: Upload to Codecov
        run: curl -s https://codecov.io/bash | bash  # Last time I'm trusting you, codecov. https://about.codecov.io/security-update/
